### PR TITLE
Fix Links

### LINKED ISSUE #5: Links not rendered clickable
**Repro steps**:

1. Generate this resume
```
#header John Doe
hello@example.com
example.com
```
2. Open PDF in Preview.app, mail and link are clickable.
3. Open PDF in Chrome, mail is clickable but the link is not.

I assume Preview makes the link clickable.

### PR DESCRIPTION
**Pull request by mmathys**
closes #5

### CODE REVIEW

**Comment by mmathys** [comment]
Should work now — the autolinker package didn't convert mails properly, fixed it in fork. Lmk what you think.

**Review by cnnmon — APPROVED** [review]
this is awesome! thank you!

**Comment by mmathys** [comment]
bump

**Review by cnnmon — APPROVED** [review]

**Comment by cnnmon** [comment]
> bump

just merged it in! had to fix some packages that were blocking deployment so sorry it took so long, and thanks for the contribution!

**Pull request merged**
